spring.application.name=employee-directory

spring.datasource.url=jdbc:mysql://localhost:3306/employee-directory
spring.datasource.username=root
spring.datasource.password=password
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url = jdbc:mysql://localhost:3306/<your_schema>

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
